schema: ./apps/server/schema.graphql
documents: ./apps/web/src/api/**/*.{graphql,tsx,jsx,ts,js}
extensions:
  codegen:
    generates:
      ./apps/server/src/types/gql.ts:
        plugins:
          - typescript
          - typescript-resolvers
        # config:
        #   scalars:
        #     ID:
        #       # ID is a number in the database nowerdays. Maybe number is not secure enough?
        #       input: number
        #       output: number
      ./apps/web/src/types/gql.ts:
        plugins:
          - typescript
          - typescript-operations
        # config:
        #   scalars:
        #     ID:
        #       # ID is a number in the database nowerdays. Maybe number is not secure enough?
        #       input: number
        #       output: number
