# Mmmc Configuration

# # Server configuration
# mmmc:
#   port: 3000
#   cluster:
#     workersCount: 4
#   log:
#     level: info
#     color: true
#   jwt:
#     secret: 'L9XTKcqzK+3pofRRwfKEK0gGjHB8a66ITQFCELvNrjA='

# # SQLite configuration
# db:
#   file: ./db/mmmc.db
