/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ContentExample: typeof import('./.vitepress/theme/components/ContentExample.vue')['default']
    ContentExamples: typeof import('./.vitepress/theme/components/ContentExamples.vue')['default']
    ContentIntegrations: typeof import('./.vitepress/theme/components/ContentIntegrations.vue')['default']
    ContentTool: typeof import('./.vitepress/theme/components/ContentTool.vue')['default']
    ContentTools: typeof import('./.vitepress/theme/components/ContentTools.vue')['default']
    LinkGrid: typeof import('./.vitepress/theme/components/LinkGrid.vue')['default']
  }
}
